### ISSUE TITLE
Could you provide the modified source code?

### ISSUE THREAD

**Issue by hzm** [Meteorix/pyflame-server#2]
Hello, I compiler uber/pyflame。It can profile python code, but I want to profile C and python.Could you tell me how to changed it?
Thank you very much.

**Comment by Meteorix** [comment]
https://github.com/Meteorix/pyflame2/tree/c_stack here

**Comment by hzm** [comment]
> https://github.com/Meteorix/pyflame2/tree/c_stack here

Ok.Thank you.
